cd\info
arc u \pack\pack1 aaa
arc u \pack\pack2 bla cha
arc u \pack\pack3 coo 
arc u \pack\pack4 cov
arc u \pack\pack5 cua doa
arc u \pack\pack6 dra 
arc u \pack\pack7 fia 
arc u \pack\pack8 apa ciabase.exe subjects books codes
arc u \pack\pack9 lao
arc u \pack\pack10 maa ora
arc u \pack\pack11 ova
arc u \pack\pack12 inv paa
arc u \pack\pack13 pra psa
arc u \pack\pack14 taa laa
arc u \pack\pack15 int uaa
