cd\pack
pause ... INSERT DISK 1 IN A: DRIVE
copy arce.com a:
copy pack1.arc a:
copy pack2.arc a:
copy pack3.arc a:
disktest/f a:
pause ... INSERT DISK 2 IN A: DRIVE
copy arce.com a:
copy pack5.arc a:
copy pack6.arc a:
disktest/f a:
pause ... INSERT DISK 3 IN A: DRIVE
copy arce.com a:
copy pack4.arc a:
copy pack9.arc a:
copy pack10.arc a:
disktest/f a:
pause ... INSERT DISK 4 IN A: DRIVE
copy arce.com a:
copy pack12.arc a:
copy pack13.arc a:
disktest/f a:
pause ... INSERT DISK 5 IN A:DRIVE
copy arce.com a:
copy pack14.arc a:
copy pack15.arc a:
disktest/f a:
pause ... INSERT DISK 6 IN A:DRIVE
copy arce.com a:
copy pack7.arc a:
copy pack8.arc a:
copy pack11.arc a:
disktest/f a: